site_name: Deep Emotions Project Docs

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github

nav:
  - Homepage: index.md 
  - Installation: instalation.md
  - Documentation: 
    - Pipelines:
      - Data download: data_download.md
      - Data preprocess: data_preprocess.md
      - Model download: model_download.md

plugins:
  - mkdocstrings
  - search

repo_url: https://github.com/nerkulec/deepemotions